{% set name = "pythtb" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythtb-{{ version }}.tar.gz
  sha256: d31cedd0399fedc36753dac58054cafb53e4d985c4524759e00f67134bfb5374
  

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.12
    - numpy >=2.0
    - matplotlib-base >=3.9

test:
  imports:
    - pythtb
  commands:
    - pip check
  requires:
    - python
    - pip

about:
  home: https://github.com/pythtb/pythtb
  dev_url: https://github.com/pythtb/pythtb
  doc_url: https://pythtb.readthedocs.io/en/latest/
  summary: Library for constructing and analyzing tight-binding models in condensed matter physics and materials science.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - treycole
